/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import LinkedCameraImage from 'src/assets/images/IGScrapperCompGrad_linked_camera.png';
import { styled } from '@mui/material/styles';
import IgScrapperCompGrad1Image from 'src/assets/images/IGScrapperCompGrad_IG_Scrapper_Comp_Grad.png';
import ButtonConnectStroked from 'src/components/ButtonConnectStroked/ButtonConnectStroked';

const IgScrapperCompGrad1 = styled('div')({
  backgroundImage: `url(${IgScrapperCompGrad1Image})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `333px`,
  width: `254px`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `13px 45px`,
  boxSizing: `border-box`,
});

const Frame67 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Group31 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `90px`,
  width: `90px`,
  margin: `0px`,
});

const Rectangle27 = styled('div')({
  borderRadius: `16px`,
  width: `90px`,
  height: `90px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const LinkedCamera = styled('img')({
  height: `40px`,
  width: `40px`,
  position: `absolute`,
  left: `28px`,
  top: `28px`,
});

const LinkedInScrapper = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(255, 255, 255, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `-0.6px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  height: `55.33px`,
  width: `142.8px`,
  margin: `12px 0px 0px 0px`,
});

const Frame155 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `16px 0px`,
  boxSizing: `border-box`,
  margin: `26px 0px 0px 0px`,
  overflow: `hidden`,
});

const ButtonConnectStroked1 = styled(ButtonConnectStroked)(({ theme }) => ({
  margin: `0px`,
}));

function IgScrapperCompGrad(props) {
  return (
    <IgScrapperCompGrad1>
      <Frame67>
        <Group31>
          <Rectangle27></Rectangle27>
          <LinkedCamera
            src={LinkedCameraImage}
            loading="lazy"
            alt={'linked_camera'}
          />
        </Group31>
        <LinkedInScrapper>
          {`LinkedIn
Scrapper`}
        </LinkedInScrapper>
      </Frame67>
      <Frame155>
        <ButtonConnectStroked1 />
      </Frame155>
    </IgScrapperCompGrad1>
  );
}

export default IgScrapperCompGrad;
