/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import RobotImage from 'src/assets/images/NormalComponent2_robot.png';
import RImage from 'src/assets/images/NormalComponent2_r.png';
import { styled } from '@mui/material/styles';

const NormalComponent21 = styled('div')({
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `209px`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `24px 25px`,
});

const Group31 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `51.46px`,
  width: `52.87px`,
  margin: `0px`,
});

const Rectangle27 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(246, 246, 251, 1)`,
  borderRadius: `16px`,
  width: `52.87px`,
  height: `51.46px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Robot = styled('img')({
  height: `23.75px`,
  width: `24.4px`,
  position: `absolute`,
  left: `14px`,
  top: `14px`,
});

const Frame72 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `43px 0px 0px 0px`,
});

const Frame71 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Q003025 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(43, 47, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `-0.8px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  height: `31.67px`,
  width: `136.23px`,
  margin: `0px`,
}));

const DaemonUptime = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `-0.35px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  background: `linear-gradient(-97.31deg, rgba(144, 144, 144, 1) 84.32329954744112%, rgba(0, 0, 0, 1) 152.46307347661838%)`,
  backgroundClip: `text`,
  WebkitBackgroundClip: `text`,
  WebkitTextFillColor: `transparent`,
  height: `23.75px`,
  width: `117.93px`,
  margin: `0px`,
});

const IconOverview = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `20.33px`,
  height: `19.79px`,
  margin: `0px 0px 0px 43px`,
});

const Rectangle24 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(113, 102, 249, 1)`,
  borderRadius: `30px`,
  width: `20.33px`,
  height: `19.79px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const R = styled('img')({
  height: `16.15px`,
  width: `16.59px`,
  position: `absolute`,
  left: `2px`,
  top: `2px`,
});

function NormalComponent2(props) {
  return (
    <NormalComponent21>
      <Group31>
        <Rectangle27></Rectangle27>
        <Robot src={RobotImage} loading="lazy" alt={'robot'} />
      </Group31>
      <Frame72>
        <Frame71>
          <Q003025>{`00:30:25`}</Q003025>
          <DaemonUptime>{`Daemon uptime`}</DaemonUptime>
        </Frame71>
        <IconOverview>
          <Rectangle24></Rectangle24>
          <R src={RImage} loading="lazy" alt={'r'} />
        </IconOverview>
      </Frame72>
    </NormalComponent21>
  );
}

export default NormalComponent2;
