/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import CompassCalibrationImage from 'src/assets/images/NormalComponent3_compass_calibration.png';
import RImage from 'src/assets/images/NormalComponent3_r.png';
import { styled } from '@mui/material/styles';

const NormalComponent31 = styled('div')({
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `208px`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `24px 25px`,
});

const Group31 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `52px`,
  width: `54.6px`,
  margin: `0px`,
});

const Rectangle27 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(246, 246, 251, 1)`,
  borderRadius: `16px`,
  width: `54.6px`,
  height: `52px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const CompassCalibration = styled('img')({
  height: `24px`,
  width: `25.2px`,
  position: `absolute`,
  left: `15px`,
  top: `14px`,
});

const Frame92 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `43px 0px 0px 0px`,
});

const Frame91 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Q32660K = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(43, 47, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `-0.8px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  height: `32px`,
  width: `142.8px`,
  margin: `0px`,
}));

const PingsSent = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `-0.35px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  background: `linear-gradient(-100.99deg, rgba(144, 144, 144, 1) 80.88766635991634%, rgba(0, 0, 0, 1) 148.26660230917037%)`,
  backgroundClip: `text`,
  WebkitBackgroundClip: `text`,
  WebkitTextFillColor: `transparent`,
  height: `24px`,
  width: `78.75px`,
  margin: `1px 0px 0px 0px`,
});

const IconOverview = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `21px`,
  height: `20px`,
  margin: `0px 0px 0px 42px`,
});

const Rectangle24 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(113, 102, 249, 1)`,
  borderRadius: `30px`,
  width: `21px`,
  height: `20px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const R = styled('img')({
  height: `16.32px`,
  width: `17.14px`,
  position: `absolute`,
  left: `2px`,
  top: `2px`,
});

function NormalComponent3(props) {
  return (
    <NormalComponent31>
      <Group31>
        <Rectangle27></Rectangle27>
        <CompassCalibration
          src={CompassCalibrationImage}
          loading="lazy"
          alt={'compass_calibration'}
        />
      </Group31>
      <Frame92>
        <Frame91>
          <Q32660K>{`326.60 K`}</Q32660K>
          <PingsSent>{`Pings sent`}</PingsSent>
        </Frame91>
        <IconOverview>
          <Rectangle24></Rectangle24>
          <R src={RImage} loading="lazy" alt={'r'} />
        </IconOverview>
      </Frame92>
    </NormalComponent31>
  );
}

export default NormalComponent3;
