/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Frame159Image from 'src/assets/images/SocialIGCampComp_Frame_159_2.png';
import Frame1591Image from 'src/assets/images/SocialIGCampComp_Frame_159_1.png';
import Frame1592Image from 'src/assets/images/SocialIGCampComp_Frame_159.png';

const SocialIgCampComp1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `29px 19px`,
  height: `315px`,
  width: `514px`,
});

const Frame59 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const MakeASocialCampaign = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const WideComponent3 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `38px 0px 0px 0px`,
});

const Frame57 = styled('div')({
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `12px 33px`,
  margin: `0px`,
});

const LinkedIn = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame159 = styled('div')({
  backgroundImage: `url(${Frame159Image})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  width: `34px`,
  height: `34px`,
  margin: `0px 0px 0px 287px`,
  overflow: `hidden`,
});

const Frame591 = styled('div')({
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `12px 33px`,
  margin: `10px 0px 0px 0px`,
});

const LinkedIn1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame1591 = styled('div')({
  backgroundImage: `url(${Frame1591Image})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  width: `34px`,
  height: `34px`,
  margin: `0px 0px 0px 287px`,
  overflow: `hidden`,
});

const Frame58 = styled('div')({
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `12px 33px`,
  margin: `10px 0px 0px 0px`,
});

const LinkedIn2 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `20px`,
  letterSpacing: `-0.5px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px`,
});

const Frame1592 = styled('div')({
  backgroundImage: `url(${Frame1592Image})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  width: `34px`,
  height: `34px`,
  margin: `0px 0px 0px 287px`,
  overflow: `hidden`,
});

function SocialIgCampComp(props) {
  return (
    <SocialIgCampComp1>
      <Frame59>
        <MakeASocialCampaign>{`Make a social campaign `}</MakeASocialCampaign>
      </Frame59>
      <WideComponent3>
        <Frame57>
          <LinkedIn>{`LinkedIn`}</LinkedIn>
          <Frame159></Frame159>
        </Frame57>
        <Frame591>
          <LinkedIn1>{`LinkedIn`}</LinkedIn1>
          <Frame1591></Frame1591>
        </Frame591>
        <Frame58>
          <LinkedIn2>{`LinkedIn`}</LinkedIn2>
          <Frame1592></Frame1592>
        </Frame58>
      </WideComponent3>
    </SocialIgCampComp1>
  );
}

export default SocialIgCampComp;
