/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import Ellipse17Image from 'src/assets/images/AIComp1_Ellipse_17.png';
import AddImage from 'src/assets/images/AIComp1_add.png';
import { styled } from '@mui/material/styles';

const AiComp11 = styled('div')({
  border: `1px solid rgba(202, 202, 202, 1)`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `108px 68px`,
  boxSizing: `border-box`,
  height: `332px`,
  width: `252px`,
});

const Group44 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `116px`,
  height: `116px`,
  margin: `0px`,
});

const Ellipse17 = styled('img')({
  height: `116px`,
  width: `116px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const Add = styled('img')({
  height: `80px`,
  width: `80px`,
  position: `absolute`,
  left: `18px`,
  top: `18px`,
});

function AiComp1(props) {
  return (
    <AiComp11>
      <Group44>
        <Ellipse17 src={Ellipse17Image} loading="lazy" alt={'Ellipse 17'} />
        <Add src={AddImage} loading="lazy" alt={'add'} />
      </Group44>
    </AiComp11>
  );
}

export default AiComp1;
