/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Frame161Image from 'src/assets/images/SocialsIGTrafficComp_Frame_161.png';

const SocialsIgTrafficComp1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `47px 39px`,
  height: `269.58px`,
  width: `527.36px`,
});

const Frame36 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame160 = styled('div')({
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `23px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px 20px 0px 61px`,
  margin: `0px`,
});

const Group83 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `22.46px`,
  width: `167.36px`,
  margin: `0px`,
});

const Source = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `40.84px`,
  height: `22.46px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const TrafficSources = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `96.63px`,
  height: `22.46px`,
  position: `absolute`,
  left: `71px`,
  top: `0px`,
});

const Frame87 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `8px 0px 0px 0px`,
});

const Rectangle39 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(76, 215, 245, 1)`,
  borderRadius: `12px`,
  width: `15.94px`,
  height: `11.23px`,
  margin: `0px`,
}));

const Frame37 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 24px`,
});

const Direct = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `35.86px`,
  height: `22.46px`,
  margin: `0px`,
});

const Q12 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `10.96px`,
  height: `22.46px`,
  margin: `0px 0px 0px 127px`,
});

const Frame86 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `8px 0px 0px 0px`,
});

const Rectangle40 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(113, 102, 249, 1)`,
  borderRadius: `12px`,
  width: `15.94px`,
  height: `11.23px`,
  margin: `0px`,
}));

const Frame38 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 24px`,
});

const Search = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `39.85px`,
  height: `22.46px`,
  margin: `0px`,
});

const Q25 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `13.95px`,
  height: `22.46px`,
  margin: `0px 0px 0px 120px`,
});

const Frame85 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `8px 0px 0px 0px`,
});

const Rectangle41 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(225, 124, 253, 1)`,
  borderRadius: `12px`,
  width: `15.94px`,
  height: `11.23px`,
  margin: `0px`,
}));

const Frame39 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 24px`,
});

const Facebook = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `56.78px`,
  height: `22.46px`,
  margin: `0px`,
});

const Q48 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `15.94px`,
  height: `22.46px`,
  margin: `0px 0px 0px 101px`,
});

const Frame84 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `8px 0px 0px 0px`,
});

const Rectangle42 = styled('div')({
  backgroundColor: `rgba(114, 235, 191, 1)`,
  borderRadius: `12px`,
  width: `15.94px`,
  height: `11.23px`,
  margin: `0px`,
});

const Frame40 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 24px`,
});

const Instagram = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `59.77px`,
  height: `22.46px`,
  margin: `0px`,
});

const Q31 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `10.96px`,
  height: `22.46px`,
  margin: `0px 0px 0px 103px`,
});

const Frame83 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `8px 0px 0px 0px`,
});

const Rectangle43 = styled('div')({
  backgroundColor: `rgba(228, 92, 92, 1)`,
  borderRadius: `12px`,
  width: `15.94px`,
  height: `11.23px`,
  margin: `0px`,
});

const Frame41 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 24px`,
});

const Twitter = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `70px`,
  height: `23.29px`,
  margin: `0px`,
});

const Q121 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `10.96px`,
  height: `22.46px`,
  margin: `0px 0px 0px 92px`,
});

const Frame161 = styled('div')({
  backgroundImage: `url(${Frame161Image})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  width: `110px`,
  height: `110px`,
  margin: `0px 0px 0px 91px`,
  overflow: `hidden`,
});

function SocialsIgTrafficComp(props) {
  return (
    <SocialsIgTrafficComp1>
      <Frame36>
        <Frame160>
          <Group83>
            <Source>{`Source`}</Source>
            <TrafficSources>{`Traffic sources, %`}</TrafficSources>
          </Group83>
        </Frame160>
        <Frame87>
          <Rectangle39></Rectangle39>
          <Frame37>
            <Direct>{`Direct`}</Direct>
            <Q12>{`12`}</Q12>
          </Frame37>
        </Frame87>
        <Frame86>
          <Rectangle40></Rectangle40>
          <Frame38>
            <Search>{`Search`}</Search>
            <Q25>{`25`}</Q25>
          </Frame38>
        </Frame86>
        <Frame85>
          <Rectangle41></Rectangle41>
          <Frame39>
            <Facebook>{`Facebook`}</Facebook>
            <Q48>{`48`}</Q48>
          </Frame39>
        </Frame85>
        <Frame84>
          <Rectangle42></Rectangle42>
          <Frame40>
            <Instagram>{`Instagram`}</Instagram>
            <Q31>{`31`}</Q31>
          </Frame40>
        </Frame84>
        <Frame83>
          <Rectangle43></Rectangle43>
          <Frame41>
            <Twitter>{`Twitter`}</Twitter>
            <Q121>{`12`}</Q121>
          </Frame41>
        </Frame83>
      </Frame36>
      <Frame161></Frame161>
    </SocialsIgTrafficComp1>
  );
}

export default SocialsIgTrafficComp;
