/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import SideBar from 'src/components/SideBar/SideBar';
import Frame132 from 'src/components/Frame132/Frame132';
import TitleBar from 'src/components/TitleBar/TitleBar';
import BigComponent1 from 'src/components/BigComponent1/BigComponent1';
import NormalComponent3 from 'src/components/NormalComponent3/NormalComponent3';
import NormalComponent2 from 'src/components/NormalComponent2/NormalComponent2';
import NormalComponent1 from 'src/components/NormalComponent1/NormalComponent1';
import ColoredComponent from 'src/components/ColoredComponent/ColoredComponent';
import WideComponent1 from 'src/components/WideComponent1/WideComponent1';
import IgScrapperComp from 'src/components/IgScrapperComp/IgScrapperComp';
import IgScrapperCompGrad from 'src/components/IgScrapperCompGrad/IgScrapperCompGrad';
import SocialIgCampComp from 'src/components/SocialIgCampComp/SocialIgCampComp';
import SocialsIgTrafficComp from 'src/components/SocialsIgTrafficComp/SocialsIgTrafficComp';
import SocialIgComp from 'src/components/SocialIgComp/SocialIgComp';
import EMailTextComp from 'src/components/EMailTextComp/EMailTextComp';
import EMailPreferences from 'src/components/EMailPreferences/EMailPreferences';
import EMailDescription from 'src/components/EMailDescription/EMailDescription';
import EMailList from 'src/components/EMailList/EMailList';
import EMail from 'src/components/EMail/EMail';
import AiComp1 from 'src/components/AiComp1/AiComp1';
import AiComp2 from 'src/components/AiComp2/AiComp2';
import Frame136 from 'src/components/Frame136/Frame136';
import Frame135 from 'src/components/Frame135/Frame135';
import Frame134 from 'src/components/Frame134/Frame134';
import Frame133 from 'src/components/Frame133/Frame133';
import Frame58 from 'src/components/Frame58/Frame58';
import { animated, useSpring, easings } from 'react-spring';
import usePage1920X1080 from 'src/components/Page1920X1080/usePage1920X1080';

const PropertyDashboard = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  height: '100vh',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  overflow: `hidden`,
});

const SideBar1 = styled(SideBar)(({ theme }) => ({
  alignSelf: `stretch`,
  margin: `0px`,
}));

const Content = styled('div')({
  backgroundColor: `rgba(246, 246, 246, 1)`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px`,
  overflow: `hidden`,
});

const Navbar = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  margin: `0px`,
});

const Frame1321 = styled(Frame132)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `80px`,
  margin: `0px`,
}));

const TitleBar1 = styled(TitleBar)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `80px`,
  margin: `0px`,
}));

const ComponentsDashboard = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `917px`,
  margin: `0px`,
});

const FirstColumn = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame150 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame149 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const BigComponent11 = styled(BigComponent1)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `416px`,
  margin: `0px`,
}));

const Frame153 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 20px`,
});

const Frame144 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const NormalComponent31 = styled(NormalComponent3)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `208px`,
  margin: `0px`,
}));

const Frame143 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `10px 0px 0px 0px`,
});

const NormalComponent21 = styled(NormalComponent2)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `209px`,
  margin: `0px`,
}));

const Frame152 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-end`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 20px`,
});

const Frame145 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const NormalComponent11 = styled(NormalComponent1)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `208px`,
  margin: `0px`,
}));

const Frame142 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `10px 0px 0px 0px`,
});

const ColoredComponent1 = styled(ColoredComponent)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `209px`,
  margin: `0px`,
}));

const Frame151 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `12px 0px 0px 0px`,
});

const Frame137 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px 14px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const WideComponent11 = styled(WideComponent1)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `246px`,
  margin: `0px`,
}));

const Frame138 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px 13px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const WideComponent2 = styled(WideComponent1)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `246px`,
  margin: `0px`,
}));

const ComponentsLeads = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `917px`,
  margin: `0px`,
});

const Frame156 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
  overflow: `hidden`,
});

const Frame1501 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame1491 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const IgScrapperComp1 = styled(IgScrapperComp)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `333px`,
  margin: `0px`,
}));

const Frame1492 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 20px`,
});

const IgScrapperComp2 = styled(IgScrapperComp)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `333px`,
  margin: `0px`,
}));

const Frame1511 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `333px`,
  margin: `0px 0px 0px 20px`,
});

const IgScrapperComp3 = styled(IgScrapperComp)(({ theme }) => ({
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px`,
}));

const Frame1521 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 20px`,
});

const IgScrapperComp4 = styled(IgScrapperComp)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `333px`,
  margin: `0px`,
}));

const Frame1502 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `16px 0px 0px 0px`,
});

const Frame1493 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const IgScrapperComp5 = styled(IgScrapperComp)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `333px`,
  margin: `0px`,
}));

const Frame1494 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 20px`,
});

const IgScrapperCompGrad1 = styled(IgScrapperCompGrad)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `333px`,
  margin: `0px`,
}));

const Frame1512 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `333px`,
  margin: `0px 0px 0px 20px`,
});

const IgScrapperComp6 = styled(IgScrapperComp)(({ theme }) => ({
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px`,
}));

const Frame1522 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 20px`,
});

const IgScrapperComp7 = styled(IgScrapperComp)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `333px`,
  margin: `0px`,
}));

const ComponentsSocial = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `917px`,
  margin: `0px`,
});

const Framework = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
  overflow: `hidden`,
});

const FirstRow = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
  overflow: `hidden`,
});

const SmallComp1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
  overflow: `hidden`,
});

const SocialIgCampComp1 = styled(SocialIgCampComp)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `315px`,
  margin: `0px`,
}));

const SmallComp2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `28px 0px 0px 0px`,
  overflow: `hidden`,
});

const SocialsIgTrafficComp1 = styled(SocialsIgTrafficComp)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `269.58px`,
  margin: `0px`,
}));

const SecondRow = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 10px`,
  overflow: `hidden`,
});

const SocialIgComp1 = styled(SocialIgComp)(({ theme }) => ({
  width: `459px`,
  height: `609px`,
  margin: `0px`,
}));

const ComponentsEMail = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `917px`,
  margin: `0px`,
});

const EMail1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const EMailComponent = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
  overflow: `hidden`,
});

const EMailTextComp1 = styled(EMailTextComp)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `818px`,
  margin: `0px`,
}));

const Frame164 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 20px`,
  overflow: `hidden`,
});

const Frame162 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `197px`,
  width: `304px`,
  margin: `0px`,
});

const EMailPreferences1 = styled(EMailPreferences)(({ theme }) => ({
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px`,
}));

const Frame163 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `613px`,
  width: `304px`,
  margin: `9px 0px 0px 0px`,
});

const EMailDescription1 = styled(EMailDescription)(({ theme }) => ({
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px`,
}));

const ComponentsCampaign = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `917px`,
  margin: `0px`,
});

const Campaign = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame167 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `255px`,
  height: `765px`,
  margin: `0px`,
  overflow: `hidden`,
});

const EMailList1 = styled(EMailList)(({ theme }) => ({
  width: `255px`,
  height: `765px`,
  margin: `0px`,
}));

const Frame166 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 20px`,
});

const EMail2 = styled(EMail)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `749px`,
  margin: `0px`,
}));

const ComponentsAi = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `917px`,
  margin: `0px`,
});

const Campaign1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame169 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Dashed1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `8px 1px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const AiComp11 = styled(AiComp1)(({ theme }) => ({
  alignSelf: `stretch`,
  width: `248px`,
  margin: `0px`,
}));

const Dashed2 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `8px 1px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 12px`,
});

const AiComp12 = styled(AiComp1)(({ theme }) => ({
  alignSelf: `stretch`,
  width: `248px`,
  margin: `0px`,
}));

const Frame168 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `5px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 12px`,
});

const AiComp21 = styled(AiComp2)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `324px`,
  margin: `0px`,
}));

const Frame1691 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `15px 0px 0px 0px`,
});

const Dashed21 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `8px 1px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const AiComp13 = styled(AiComp1)(({ theme }) => ({
  alignSelf: `stretch`,
  width: `248px`,
  margin: `0px`,
}));

const Frame1681 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `5px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 12px`,
});

const AiComp22 = styled(AiComp2)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `324px`,
  margin: `0px`,
}));

const Dashed11 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `8px 1px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 12px`,
});

const AiComp14 = styled(AiComp1)(({ theme }) => ({
  alignSelf: `stretch`,
  width: `248px`,
  margin: `0px`,
}));

const ComponentsSettings = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `917px`,
  margin: `0px`,
});

const Settings1 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `13px 24px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `436px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Frame170 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `74px`,
  margin: `0px`,
  overflow: `hidden`,
});

const Frame1361 = styled(Frame136)(({ theme }) => ({
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px`,
}));

const Frame171 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `74px`,
  margin: `10px 0px 0px 0px`,
  overflow: `hidden`,
});

const Frame1351 = styled(Frame135)(({ theme }) => ({
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px`,
}));

const Frame172 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `74px`,
  margin: `10px 0px 0px 0px`,
  overflow: `hidden`,
});

const Frame1341 = styled(Frame134)(({ theme }) => ({
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px`,
}));

const Frame173 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `74px`,
  margin: `10px 0px 0px 0px`,
  overflow: `hidden`,
});

const Frame1331 = styled(Frame133)(({ theme }) => ({
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px`,
}));

const Frame174 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  alignSelf: `stretch`,
  height: `74px`,
  margin: `10px 0px 0px 0px`,
  overflow: `hidden`,
});

const Frame581 = styled(Frame58)(({ theme }) => ({
  alignSelf: `stretch`,
  flexGrow: `1`,
  margin: `0px`,
}));

function Page1920X1080(props) {
  const { data, fns } = usePage1920X1080();

  const switchStateToPropertyDashboard = (
    duration = 0,
    delay = 0,
    easing = 'linear'
  ) => {};

  const switchStateToPropertyLeads = (
    duration = 0,
    delay = 0,
    easing = 'linear'
  ) => {};

  const switchStateToPropertySocial = (
    duration = 0,
    delay = 0,
    easing = 'linear'
  ) => {};

  const switchStateToPropertyEMail = (
    duration = 0,
    delay = 0,
    easing = 'linear'
  ) => {};

  const switchStateToPropertyCampaign = (
    duration = 0,
    delay = 0,
    easing = 'linear'
  ) => {};

  const switchStateToPropertyAI = (
    duration = 0,
    delay = 0,
    easing = 'linear'
  ) => {};

  const switchStateToPropertySettings = (
    duration = 0,
    delay = 0,
    easing = 'linear'
  ) => {};
  return (
    <PropertyDashboard
      onClick={() => {
        switchStateToPropertyAI(750, 250, 'easeOutQuart');
        fns.setCurrentVariant('PropertyAI');
      }}
    >
      <SideBar1 />
      <Content
        onClick={() => {
          switchStateToPropertyDashboard(0, 1250, 'easeInOutBack');
          fns.setCurrentVariant('PropertyDashboard');
        }}
      >
        <Navbar>
          <Frame1321 />
          <TitleBar1 />
        </Navbar>
        {!(data.currentVariant === 'PropertyLeads') &&
          !(data.currentVariant === 'PropertySocial') &&
          !(data.currentVariant === 'PropertyEMail') &&
          !(data.currentVariant === 'PropertyCampaign') &&
          !(data.currentVariant === 'PropertyAI') &&
          !(data.currentVariant === 'PropertySettings') && (
            <ComponentsDashboard>
              <FirstColumn>
                <Frame150>
                  <Frame149>
                    <BigComponent11 />
                  </Frame149>
                  <Frame153>
                    <Frame144>
                      <NormalComponent31 />
                    </Frame144>
                    <Frame143>
                      <NormalComponent21 />
                    </Frame143>
                  </Frame153>
                  <Frame152>
                    <Frame145>
                      <NormalComponent11 />
                    </Frame145>
                    <Frame142>
                      <ColoredComponent1 />
                    </Frame142>
                  </Frame152>
                </Frame150>
                <Frame151>
                  <Frame137>
                    <WideComponent11 />
                  </Frame137>
                  <Frame138>
                    <WideComponent2 />
                  </Frame138>
                </Frame151>
              </FirstColumn>
            </ComponentsDashboard>
          )}
        {data.currentVariant === 'PropertyLeads' && (
          <ComponentsLeads>
            <Frame156>
              <Frame1501>
                <Frame1491>
                  <IgScrapperComp1 />
                </Frame1491>
                <Frame1492>
                  <IgScrapperComp2 />
                </Frame1492>
                <Frame1511>
                  <IgScrapperComp3 />
                </Frame1511>
                <Frame1521>
                  <IgScrapperComp4 />
                </Frame1521>
              </Frame1501>
              <Frame1502
                onClick={() => {
                  switchStateToPropertySocial(100, 100, 'easeOutQuart');
                  fns.setCurrentVariant('PropertySocial');
                }}
              >
                <Frame1493>
                  <IgScrapperComp5 />
                </Frame1493>
                <Frame1494>
                  <IgScrapperCompGrad1 />
                </Frame1494>
                <Frame1512>
                  <IgScrapperComp6 />
                </Frame1512>
                <Frame1522>
                  <IgScrapperComp7 />
                </Frame1522>
              </Frame1502>
            </Frame156>
          </ComponentsLeads>
        )}
        {data.currentVariant === 'PropertySocial' && (
          <ComponentsSocial>
            <Framework
              onClick={() => {
                switchStateToPropertyDashboard(750, 250, 'easeOutQuart');
                fns.setCurrentVariant('PropertyDashboard');
              }}
            >
              <FirstRow>
                <SmallComp1>
                  <SocialIgCampComp1 />
                </SmallComp1>
                <SmallComp2>
                  <SocialsIgTrafficComp1 />
                </SmallComp2>
              </FirstRow>
              <SecondRow>
                <SocialIgComp1 />
              </SecondRow>
            </Framework>
          </ComponentsSocial>
        )}
        {data.currentVariant === 'PropertyEMail' && (
          <ComponentsEMail>
            <EMail1>
              <EMailComponent>
                <EMailTextComp1 />
              </EMailComponent>
              <Frame164>
                <Frame162>
                  <EMailPreferences1 />
                </Frame162>
                <Frame163>
                  <EMailDescription1 />
                </Frame163>
              </Frame164>
            </EMail1>
          </ComponentsEMail>
        )}
        {data.currentVariant === 'PropertyCampaign' && (
          <ComponentsCampaign>
            <Campaign>
              <Frame167>
                <EMailList1 />
              </Frame167>
              <Frame166>
                <EMail2 />
              </Frame166>
            </Campaign>
          </ComponentsCampaign>
        )}
        {data.currentVariant === 'PropertyAI' && (
          <ComponentsAi>
            <Campaign1>
              <Frame169>
                <Dashed1>
                  <AiComp11 />
                </Dashed1>
                <Dashed2>
                  <AiComp12 />
                </Dashed2>
                <Frame168>
                  <AiComp21 />
                </Frame168>
              </Frame169>
              <Frame1691>
                <Dashed21>
                  <AiComp13 />
                </Dashed21>
                <Frame1681>
                  <AiComp22 />
                </Frame1681>
                <Dashed11>
                  <AiComp14 />
                </Dashed11>
              </Frame1691>
            </Campaign1>
          </ComponentsAi>
        )}
        {data.currentVariant === 'PropertySettings' && (
          <ComponentsSettings>
            <Settings1>
              <Frame170>
                <Frame1361 />
              </Frame170>
              <Frame171>
                <Frame1351 />
              </Frame171>
              <Frame172>
                <Frame1341 />
              </Frame172>
              <Frame173>
                <Frame1331 />
              </Frame173>
              <Frame174>
                <Frame581 />
              </Frame174>
            </Settings1>
          </ComponentsSettings>
        )}
      </Content>
    </PropertyDashboard>
  );
}

export default Page1920X1080;
