/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';

const EMail1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `25px 321px 484px 26px`,
  height: `993.6px`,
  width: `1100px`,
});

const Frame141 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `753px`,
  margin: `0px`,
});

const EMailExample1 = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
});

const Rectangle49 = styled('div')({
  backgroundColor: `rgba(217, 217, 217, 1)`,
  height: `1px`,
  width: `753px`,
  margin: `6px 0px 0px 0px`,
});

const HiExample1LoremIpsum = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `400`,
  fontSize: `16px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `735.54px`,
  margin: `34px 0px 0px 0px`,
});

function EMail(props) {
  return (
    <EMail1>
      <Frame141>
        <EMailExample1>{`E-Mail example 1`}</EMailExample1>
        <Rectangle49></Rectangle49>
      </Frame141>
      <HiExample1LoremIpsum>
        {`Hi Example 1!

Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Habitant morbi tristique senectus et. Nec dui nunc mattis enim ut tellus elementum. Sem fringilla ut morbi tincidunt augue interdum velit euismod. Id consectetur purus ut faucibus pulvinar elementum integer enim neque. Convallis a cras semper auctor neque vitae. Turpis massa tincidunt dui ut ornare. Fames ac turpis egestas sed tempus urna. Lacus viverra vitae congue eu consequat ac felis donec et. Est velit egestas dui id ornare arcu odio ut. Ut sem nulla pharetra diam sit amet.

Nisl suscipit adipiscing bibendum est. Sed vulputate odio ut enim blandit volutpat maecenas. Venenatis tellus in metus vulputate eu scelerisque felis. A lacus vestibulum sed arcu non. Ut tellus elementum sagittis vitae et leo duis ut. Suspendisse interdum consectetur libero id faucibus nisl tincidunt eget. Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus. Amet risus nullam eget felis eget nunc lobortis mattis. Mattis molestie a iaculis at erat pellentesque adipiscing commodo elit. Blandit volutpat maecenas volutpat blandit aliquam etiam erat velit. Adipiscing commodo elit at imperdiet dui accumsan. Et tortor at risus viverra adipiscing at in.

Best Regards,
NetWise`}
      </HiExample1LoremIpsum>
    </EMail1>
  );
}

export default EMail;
