/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Q3Variants from 'src/components/Q3Variants/Q3Variants';
import ButtonOptimal from 'src/components/ButtonOptimal/ButtonOptimal';
import ButtonGenerate from 'src/components/ButtonGenerate/ButtonGenerate';

const EMailDescription1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(113, 102, 249, 1)`,
  boxSizing: `border-box`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `19px 14px`,
  height: `635px`,
  width: `304px`,
});

const Frame84 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Description = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(113, 102, 249, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
}));

const Frame76 = styled('div')({
  border: `1px solid rgba(113, 102, 249, 1)`,
  boxSizing: `border-box`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `12px 14px`,
  height: `441px`,
  width: `276px`,
  margin: `16px 0px 0px 0px`,
});

const BusinessNetworkManag = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(189, 186, 186, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  width: `224px`,
  margin: `0px`,
});

const Frame841 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `16px 0px 0px 0px`,
});

const NumberOfVariants = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(113, 102, 249, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px`,
}));

const CreativityLevel = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(113, 102, 249, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 16px`,
}));

const Frame842 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `78px`,
  width: `252px`,
  margin: `16px 0px 0px 0px`,
});

const Frame843 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Q3Variants1 = styled(Q3Variants)(({ theme }) => ({
  margin: `0px`,
}));

const ButtonOptimal1 = styled(ButtonOptimal)(({ theme }) => ({
  margin: `0px 0px 0px 24px`,
}));

const ButtonGenerate1 = styled(ButtonGenerate)(({ theme }) => ({
  margin: `16px 0px 0px 0px`,
}));

function EMailDescription(props) {
  return (
    <EMailDescription1>
      <Frame84>
        <Description>{`Description`}</Description>
        <Frame76>
          <BusinessNetworkManag>
            {`BUSINESS NETWORK MANAGEMENT

- Client Lead Generation
- Client Outreach(Automated Campaigns, integration with lemlist)
- Brand regional/international leads focused on customer requests
- Statistic insight on network leads reach
- CopyWriting(E-mail/content posts)
- Network Management
`}
          </BusinessNetworkManag>
        </Frame76>
      </Frame84>
      <Frame841>
        <NumberOfVariants>{`Number of variants`}</NumberOfVariants>
        <CreativityLevel>{`Creativity level`}</CreativityLevel>
      </Frame841>
      <Frame842>
        <Frame843>
          <Q3Variants1 />
          <ButtonOptimal1 />
        </Frame843>
        <ButtonGenerate1 />
      </Frame842>
    </EMailDescription1>
  );
}

export default EMailDescription;
