/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import RImage from 'src/assets/images/TitleBar_r.png';
import { styled } from '@mui/material/styles';

const Property1Overview = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  width: '100%',
  justifyContent: `space-between`,
  alignItems: `center`,
  padding: `10px 18px`,
  boxSizing: `border-box`,
  height: `72px`,
});

const Frame134 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Settings = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `-0.8px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px 0px 0px 16px`,
});

const CampaignManager = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `-0.8px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px 0px 0px 16px`,
});

const AiGenerator = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `-0.8px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px 0px 0px 16px`,
});

const EMailGenerator = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `-0.8px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px 0px 0px 16px`,
});

const SocialNetworkManagem = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `-0.8px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px 0px 0px 16px`,
});

const LeadGeneration = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `-0.8px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px 0px 0px 16px`,
});

const StatisticOverview = styled('div')({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `-0.8px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px`,
});

const IconOverview = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `34px`,
  height: `34px`,
  margin: `0px 0px 0px 16px`,
});

const Rectangle23 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(246, 246, 251, 1)`,
  borderRadius: `30px`,
  width: `34px`,
  height: `34px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const Rectangle24 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(113, 102, 249, 1)`,
  borderRadius: `30px`,
  width: `20px`,
  height: `20px`,
  position: `absolute`,
  left: `7px`,
  top: `7px`,
}));

const R = styled('img')({
  height: `16.32px`,
  width: `16.32px`,
  position: `absolute`,
  left: `9px`,
  top: `9px`,
});

const TimePeriod = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Item1Active = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(113, 102, 249, 1)`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `10px 24px`,
  boxSizing: `border-box`,
  margin: `0px`,
}));

const Q30Days = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(237, 237, 250, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `-0.07px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px`,
}));

const Item1Normal = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(237, 237, 250, 1)`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `10px 24px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 23px`,
}));

const Q90Days = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(43, 47, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `-0.07px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px`,
}));

const Item1Normal1 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(237, 237, 250, 1)`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `10px 24px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 23px`,
}));

const Q90Days1 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(43, 47, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `-0.07px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px`,
}));

const Item1Normal2 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(237, 237, 250, 1)`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `10px 24px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 23px`,
}));

const Q10Months = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(43, 47, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `-0.07px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px`,
}));

const TimePeriodHidden = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Item1Active1 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(246, 246, 246, 1)`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `10px 24px`,
  boxSizing: `border-box`,
  margin: `0px`,
}));

const Q30Days1 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(246, 246, 246, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `-0.07px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px`,
}));

const Item1Normal3 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(246, 246, 246, 1)`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `10px 24px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 23px`,
}));

const Q90Days2 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(246, 246, 246, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `-0.07px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px`,
}));

const Item1Normal4 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(246, 246, 246, 1)`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `10px 24px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 23px`,
}));

const Q90Days3 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(246, 246, 246, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `-0.07px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px`,
}));

const Item1Normal5 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(246, 246, 246, 1)`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `10px 24px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 23px`,
}));

const Q10Months1 = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(246, 246, 246, 1)`,
  fontStyle: `normal`,
  fontFamily: `Quicksand`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `-0.07px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  margin: `0px`,
}));

function TitleBar(props) {
  return (
    <Property1Overview>
      <Frame134>
        {false && <Settings>{`Settings`}</Settings>}
        {false && <CampaignManager>{`Campaign Manager`}</CampaignManager>}
        {false && <AiGenerator>{`AI Generator`}</AiGenerator>}
        {false && <EMailGenerator>{`E-Mail Generator`}</EMailGenerator>}
        {false && (
          <SocialNetworkManagem>
            {`Social Network Management`}
          </SocialNetworkManagem>
        )}
        {false && <LeadGeneration>{`Lead Generation`}</LeadGeneration>}
        <StatisticOverview>{`Statistic overview`}</StatisticOverview>
        <IconOverview>
          <Rectangle23></Rectangle23>
          <Rectangle24></Rectangle24>
          <R src={RImage} loading="lazy" alt={'r'} />
        </IconOverview>
      </Frame134>
      <TimePeriod>
        <Item1Active>
          <Q30Days>{`30 days`}</Q30Days>
        </Item1Active>
        <Item1Normal>
          <Q90Days>{`90 days`}</Q90Days>
        </Item1Normal>
        <Item1Normal1>
          <Q90Days1>{`5 months`}</Q90Days1>
        </Item1Normal1>
        <Item1Normal2>
          <Q10Months>{`10 months`}</Q10Months>
        </Item1Normal2>
      </TimePeriod>
      {false && (
        <TimePeriodHidden>
          <Item1Active1>
            <Q30Days1>{`30 days`}</Q30Days1>
          </Item1Active1>
          <Item1Normal3>
            <Q90Days2>{`90 days`}</Q90Days2>
          </Item1Normal3>
          <Item1Normal4>
            <Q90Days3>{`5 months`}</Q90Days3>
          </Item1Normal4>
          <Item1Normal5>
            <Q10Months1>{`10 months`}</Q10Months1>
          </Item1Normal5>
        </TimePeriodHidden>
      )}
    </Property1Overview>
  );
}

export default TitleBar;
