/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import AreaChartImage from 'src/assets/images/ColoredComponent_area_chart.png';
import RImage from 'src/assets/images/ColoredComponent_r.png';
import { styled } from '@mui/material/styles';

const ColoredComponent1 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(76, 215, 245, 1)`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `209px`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `24px 25px`,
  boxSizing: `border-box`,
}));

const Group31 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `52.27px`,
  width: `54.6px`,
  margin: `0px`,
});

const Rectangle27 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 0.15)`,
  borderRadius: `16px`,
  width: `54.6px`,
  height: `52.27px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
});

const AreaChart = styled('img')({
  height: `24.13px`,
  width: `25.2px`,
  position: `absolute`,
  left: `15px`,
  top: `14px`,
});

const Frame65 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `43px 0px 0px 0px`,
});

const Frame66 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Q4234 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(246, 246, 251, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `-0.8px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  height: `32.17px`,
  width: `120.75px`,
  margin: `0px`,
}));

const ResponseRate = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(246, 246, 251, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `-0.35px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  height: `24.13px`,
  width: `110.25px`,
  margin: `0px`,
}));

const IconOverview = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `21px`,
  height: `20.1px`,
  margin: `0px 0px 0px 64px`,
});

const Rectangle24 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(246, 246, 251, 1)`,
  borderRadius: `30px`,
  width: `21px`,
  height: `20.1px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const R = styled('img')({
  height: `16.4px`,
  width: `17.14px`,
  position: `absolute`,
  left: `2px`,
  top: `2px`,
});

function ColoredComponent(props) {
  return (
    <ColoredComponent1>
      <Group31>
        <Rectangle27></Rectangle27>
        <AreaChart src={AreaChartImage} loading="lazy" alt={'area_chart'} />
      </Group31>
      <Frame65>
        <Frame66>
          <Q4234>{`42,34%`}</Q4234>
          <ResponseRate>{`Response Rate`}</ResponseRate>
        </Frame66>
        <IconOverview>
          <Rectangle24></Rectangle24>
          <R src={RImage} loading="lazy" alt={'r'} />
        </IconOverview>
      </Frame65>
    </ColoredComponent1>
  );
}

export default ColoredComponent;
