/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Contact from 'src/components/Contact/Contact';

const EMailList1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  border: `1px solid rgba(113, 102, 249, 1)`,
  boxSizing: `border-box`,
  borderRadius: `23px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: 'auto',
  width: 'fit-content',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `21px 13px`,
  overflow: `hidden`,
});

const Contact1 = styled(Contact)(({ theme }) => ({
  margin: `0px`,
}));

const Contact2 = styled(Contact)(({ theme }) => ({
  margin: `10px 0px 0px 0px`,
}));

const Contact3 = styled(Contact)(({ theme }) => ({
  margin: `10px 0px 0px 0px`,
}));

const Contact4 = styled(Contact)(({ theme }) => ({
  margin: `10px 0px 0px 0px`,
}));

const Contact5 = styled(Contact)(({ theme }) => ({
  margin: `10px 0px 0px 0px`,
}));

const Contact6 = styled(Contact)(({ theme }) => ({
  margin: `10px 0px 0px 0px`,
}));

const Contact7 = styled(Contact)(({ theme }) => ({
  margin: `10px 0px 0px 0px`,
}));

const Contact8 = styled(Contact)(({ theme }) => ({
  margin: `10px 0px 0px 0px`,
}));

const Contact9 = styled(Contact)(({ theme }) => ({
  margin: `10px 0px 0px 0px`,
}));

const Contact10 = styled(Contact)(({ theme }) => ({
  margin: `10px 0px 0px 0px`,
}));

function EMailList(props) {
  return (
    <EMailList1>
      <Contact1 />
      <Contact2 />
      <Contact3 />
      <Contact4 />
      <Contact5 />
      <Contact6 />
      <Contact7 />
      <Contact8 />
      <Contact9 />
      <Contact10 />
    </EMailList1>
  );
}

export default EMailList;
