/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import AttachEmailImage from 'src/assets/images/NormalComponent1_attach_email.png';
import RImage from 'src/assets/images/NormalComponent1_r.png';
import { styled } from '@mui/material/styles';

const NormalComponent11 = styled('div')({
  boxShadow: `2px 4px 4px rgba(0, 0, 0, 0.25)`,
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `208px`,
  width: '100%',
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `23px 25px`,
});

const Group31 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  height: `52.27px`,
  width: `53.95px`,
  margin: `0px`,
});

const Rectangle27 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(246, 246, 251, 1)`,
  borderRadius: `16px`,
  width: `53.95px`,
  height: `52.27px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const AttachEmail = styled('img')({
  height: `24.13px`,
  width: `24.9px`,
  position: `absolute`,
  left: `16px`,
  top: `16px`,
});

const Frame70 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-end`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `42px 0px 0px 0px`,
});

const Frame69 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-end`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame68 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Q525 = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(43, 47, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `-0.8px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  height: `32.17px`,
  width: `58.1px`,
  margin: `0px`,
}));

const EMailsSent = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `-0.35px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  background: `linear-gradient(-99.78deg, rgba(144, 144, 144, 1) 82.15060930366266%, rgba(0, 0, 0, 1) 149.80716452078224%)`,
  backgroundClip: `text`,
  WebkitBackgroundClip: `text`,
  WebkitTextFillColor: `transparent`,
  height: `24.13px`,
  width: `89.22px`,
  margin: `0px`,
});

const IconOverview = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  width: `20.75px`,
  height: `20.1px`,
  margin: `0px 0px 0px 93px`,
});

const Rectangle24 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(113, 102, 249, 1)`,
  borderRadius: `30px`,
  width: `20.75px`,
  height: `20.1px`,
  position: `absolute`,
  left: `0px`,
  top: `0px`,
}));

const R = styled('img')({
  height: `16.4px`,
  width: `16.93px`,
  position: `absolute`,
  left: `2px`,
  top: `2px`,
});

function NormalComponent1(props) {
  return (
    <NormalComponent11>
      <Group31>
        <Rectangle27></Rectangle27>
        <AttachEmail
          src={AttachEmailImage}
          loading="lazy"
          alt={'attach_email'}
        />
      </Group31>
      <Frame70>
        <Frame69>
          <Frame68>
            <Q525>{`525`}</Q525>
            <EMailsSent>{`E-mails sent`}</EMailsSent>
          </Frame68>
          <IconOverview>
            <Rectangle24></Rectangle24>
            <R src={RImage} loading="lazy" alt={'r'} />
          </IconOverview>
        </Frame69>
      </Frame70>
    </NormalComponent11>
  );
}

export default NormalComponent1;
