/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import InstagramIconIcons1Image from 'src/assets/images/IGScrapperComp_Instagram_icon_icons_1.png';
import { styled } from '@mui/material/styles';
import ButtonConnect from 'src/components/ButtonConnect/ButtonConnect';

const IgScrapperComp1 = styled('div')({
  backgroundColor: `rgba(255, 255, 255, 1)`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `333px`,
  width: `254px`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `13px 45px`,
  boxSizing: `border-box`,
});

const Frame103 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const InstagramIconIcons1 = styled('img')({
  height: `40px`,
  width: `40px`,
  objectFit: `cover`,
  margin: `0px`,
});

const InstagramScrapper = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(43, 47, 66, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `24px`,
  letterSpacing: `-0.6px`,
  textDecoration: `none`,
  lineHeight: `32px`,
  textTransform: `none`,
  height: `55.33px`,
  width: `142.8px`,
  margin: `58px 0px 0px 0px`,
}));

const Frame155 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `16px 0px`,
  boxSizing: `border-box`,
  margin: `26px 0px 0px 0px`,
  overflow: `hidden`,
});

const ButtonConnect1 = styled(ButtonConnect)(({ theme }) => ({
  alignSelf: `stretch`,
  height: `36px`,
  margin: `0px`,
}));

function IgScrapperComp(props) {
  return (
    <IgScrapperComp1>
      <Frame103>
        <InstagramIconIcons1
          src={InstagramIconIcons1Image}
          loading="lazy"
          alt={'Instagram_icon-icons 1'}
        />
        <InstagramScrapper>{`Instagram Scrapper`}</InstagramScrapper>
      </Frame103>
      <Frame155>
        <ButtonConnect1 />
      </Frame155>
    </IgScrapperComp1>
  );
}

export default IgScrapperComp;
