/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Frame136Image from 'src/assets/images/WideComponent1_Frame_136.png';

const WideComponent11 = styled('div')({
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `246px`,
  width: `561px`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `18px 42px`,
});

const Frame76 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const TraficSources = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `-0.35px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  height: `23.14px`,
  width: `98.63px`,
  margin: `0px`,
});

const Rectangle36 = styled('div')({
  backgroundColor: `rgba(217, 217, 217, 1)`,
  height: `0.96px`,
  width: `423.39px`,
  margin: `3px 0px 0px 0px`,
});

const Frame88 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `13px 0px 0px 0px`,
});

const Frame85 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px`,
});

const Frame83 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(246, 246, 251, 1)`,
  borderRadius: `11px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `0px 23px`,
  boxSizing: `border-box`,
  margin: `0px`,
}));

const Source = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(167, 167, 167, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  margin: `0px`,
});

const TrafficSources = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(167, 167, 167, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  margin: `0px 0px 0px 75px`,
});

const Frame84 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  justifyContent: `space-between`,
  alignItems: `flex-start`,
  padding: `0px 5px`,
  boxSizing: `border-box`,
  height: `116px`,
  width: `223px`,
  margin: `6px 0px 0px 0px`,
});

const Frame82 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Rectangle39 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(76, 215, 245, 1)`,
  borderRadius: `12px`,
  width: `15.94px`,
  height: `11.57px`,
  margin: `0px`,
}));

const Frame37 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 24px`,
});

const Direct = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `35.86px`,
  height: `23.14px`,
  margin: `0px`,
});

const Q12 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `10.96px`,
  height: `23.14px`,
  margin: `0px 0px 0px 127px`,
});

const Frame81 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Rectangle40 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(113, 102, 249, 1)`,
  borderRadius: `12px`,
  width: `15.94px`,
  height: `11.57px`,
  margin: `0px`,
}));

const Frame38 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 24px`,
});

const Search = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `39.85px`,
  height: `23.14px`,
  margin: `0px`,
});

const Q25 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `13.95px`,
  height: `23.14px`,
  margin: `0px 0px 0px 120px`,
});

const Frame80 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Rectangle41 = styled('div')(({ theme }) => ({
  backgroundColor: `rgba(225, 124, 253, 1)`,
  borderRadius: `12px`,
  width: `15.94px`,
  height: `11.57px`,
  margin: `0px`,
}));

const Frame39 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 24px`,
});

const Facebook = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `56.78px`,
  height: `23.14px`,
  margin: `0px`,
});

const Q48 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `15.94px`,
  height: `23.14px`,
  margin: `0px 0px 0px 101px`,
});

const Frame79 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Rectangle42 = styled('div')({
  backgroundColor: `rgba(114, 235, 191, 1)`,
  borderRadius: `12px`,
  width: `15.94px`,
  height: `11.57px`,
  margin: `0px`,
});

const Frame40 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 24px`,
});

const Instagram = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `59.77px`,
  height: `23.14px`,
  margin: `0px`,
});

const Q31 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `10.96px`,
  height: `23.14px`,
  margin: `0px 0px 0px 103px`,
});

const Frame78 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  padding: `0px`,
  boxSizing: `border-box`,
});

const Rectangle43 = styled('div')({
  backgroundColor: `rgba(228, 92, 92, 1)`,
  borderRadius: `12px`,
  width: `15.94px`,
  height: `11.57px`,
  margin: `0px`,
});

const Frame41 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `0px`,
  boxSizing: `border-box`,
  margin: `0px 0px 0px 24px`,
});

const Twitter = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `70px`,
  height: `24px`,
  margin: `0px`,
});

const Q121 = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `400`,
  fontSize: `12px`,
  letterSpacing: `-0.3px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `10.96px`,
  height: `23.14px`,
  margin: `0px 0px 0px 92px`,
});

const Frame136 = styled('div')({
  backgroundImage: `url(${Frame136Image})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  width: `110px`,
  height: `110px`,
  margin: `0px 0px 0px 63px`,
});

function WideComponent1(props) {
  return (
    <WideComponent11>
      <Frame76>
        <TraficSources>{`Trafic Sources`}</TraficSources>
        <Rectangle36></Rectangle36>
      </Frame76>
      <Frame88>
        <Frame85>
          <Frame83>
            <Source>{`Source`}</Source>
            <TrafficSources>{`Traffic sources, %`}</TrafficSources>
          </Frame83>
          <Frame84>
            <Frame82>
              <Rectangle39></Rectangle39>
              <Frame37>
                <Direct>{`Direct`}</Direct>
                <Q12>{`12`}</Q12>
              </Frame37>
            </Frame82>
            <Frame81>
              <Rectangle40></Rectangle40>
              <Frame38>
                <Search>{`Search`}</Search>
                <Q25>{`25`}</Q25>
              </Frame38>
            </Frame81>
            <Frame80>
              <Rectangle41></Rectangle41>
              <Frame39>
                <Facebook>{`Facebook`}</Facebook>
                <Q48>{`48`}</Q48>
              </Frame39>
            </Frame80>
            <Frame79>
              <Rectangle42></Rectangle42>
              <Frame40>
                <Instagram>{`Instagram`}</Instagram>
                <Q31>{`31`}</Q31>
              </Frame40>
            </Frame79>
            <Frame78>
              <Rectangle43></Rectangle43>
              <Frame41>
                <Twitter>{`Twitter`}</Twitter>
                <Q121>{`12`}</Q121>
              </Frame41>
            </Frame78>
          </Frame84>
        </Frame85>
        <Frame136></Frame136>
      </Frame88>
    </WideComponent11>
  );
}

export default WideComponent1;
