/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import ViewHeadlineImage from 'src/assets/images/EMailTagline_view_headline.png';
import { styled } from '@mui/material/styles';

const EMailTagline1 = styled('div')({
  border: `1px solid rgba(113, 102, 249, 1)`,
  boxSizing: `border-box`,
  borderRadius: `20px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `center`,
  alignItems: `center`,
  padding: `10px 16px`,
  height: `44px`,
  width: `183px`,
});

const ViewHeadline = styled('img')({
  height: `24px`,
  width: `24px`,
  margin: `0px`,
});

const TaglineHeadline = styled('div')(({ theme }) => ({
  textAlign: `center`,
  whiteSpace: `pre-wrap`,
  color: `rgba(113, 102, 249, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `12px`,
  letterSpacing: `0px`,
  textDecoration: `none`,
  textTransform: `none`,
  margin: `0px 0px 0px 21px`,
}));

function EMailTagline(props) {
  return (
    <EMailTagline1>
      <ViewHeadline
        src={ViewHeadlineImage}
        loading="lazy"
        alt={'view_headline'}
      />
      <TaglineHeadline>{`Tagline Headline`}</TaglineHeadline>
    </EMailTagline1>
  );
}

export default EMailTagline;
