/**********************************************************************
 *
 *   Component generated by Quest
 *
 *   WARNING: By editing this component by hand, you will lose the ability to regenerate the code without conflicts.
 *   To preseve that abilty, always export from Quest to regenerate this file.
 *   To setup props, bindings and actions, use the Quest editor
 *   Code Logic goes in the hook associated with this component
 *
 *   For help and further details refer to: https://www.quest.ai/docs
 *
 *
 **********************************************************************/

import React from 'react';
import { styled } from '@mui/material/styles';
import Frame35Image from 'src/assets/images/BigComponent1_Frame_35.png';

const BigComponent11 = styled('div')({
  boxShadow: `0px 4px 4px rgba(0, 0, 0, 0.25)`,
  border: `1px solid rgba(0, 0, 0, 1)`,
  boxSizing: `border-box`,
  borderRadius: `32px`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `column`,
  height: `416px`,
  width: '100%',
  justifyContent: `space-between`,
  alignItems: `flex-start`,
  padding: `23px 25px`,
});

const Frame33 = styled('div')({
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `flex-start`,
  padding: `6px 10px`,
  boxSizing: `border-box`,
});

const TotalVisits = styled('div')({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(0, 0, 0, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `14px`,
  letterSpacing: `-0.35px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `76.26px`,
  height: `19.23px`,
  margin: `0px`,
});

const Q4243M = styled('div')(({ theme }) => ({
  textAlign: `left`,
  whiteSpace: `pre-wrap`,
  color: `rgba(113, 102, 249, 1)`,
  fontStyle: `normal`,
  fontFamily: `Montserrat`,
  fontWeight: `700`,
  fontSize: `32px`,
  letterSpacing: `-0.8px`,
  textDecoration: `none`,
  lineHeight: `24px`,
  textTransform: `none`,
  width: `120.57px`,
  height: `19.23px`,
  margin: `0px 0px 0px 261px`,
}));

const Frame35 = styled('div')({
  backgroundImage: `url(${Frame35Image})`,
  backgroundPosition: `center`,
  backgroundSize: `cover`,
  backgroundRepeat: `no-repeat`,
  display: `flex`,
  position: `relative`,
  isolation: `isolate`,
  flexDirection: `row`,
  justifyContent: `flex-start`,
  alignItems: `center`,
  height: `303px`,
  width: `468px`,
});

function BigComponent1(props) {
  return (
    <BigComponent11>
      <Frame33>
        <TotalVisits>{`Total visits`}</TotalVisits>
        <Q4243M>{`42.43M`}</Q4243M>
      </Frame33>
      <Frame35></Frame35>
    </BigComponent11>
  );
}

export default BigComponent1;
